<?php
// Additive declaration: define editor baseline once, then admin-only deltas.

$editorCapabilities = [
    // Editors can assign collective terms via taxonomy assign_terms = edit_posts,
    // but they cannot manage/create/delete terms.
    'edit_event',
    'read_event',
    'delete_event',
    'edit_events',
    'publish_events',
    'read_private_events',
    'edit_published_events',
    'edit_collective',
    'read_collective',
    'delete_collective',
    'edit_collectives',
    'publish_collectives',
    'read_private_collectives',
    'edit_published_collectives',
    'edit_news_item',
    'read_news_item',
    'delete_news_item',
    'edit_news_items',
    'publish_news_items',
    'read_private_news_items',
    'edit_published_news_items',
    'edit_press_item',
    'read_press_item',
    'delete_press_item',
    'edit_press_items',
    'publish_press_items',
    'read_private_press_items',
    'edit_published_press_items',
];

$administratorExtraCapabilities = [
    'manage_event_type_associations',
    'manage_collective_associations',
    'edit_others_events',
    'delete_events',
    'delete_private_events',
    'delete_published_events',
    'delete_others_events',
    'edit_private_events',
    'edit_others_collectives',
    'delete_collectives',
    'delete_private_collectives',
    'delete_published_collectives',
    'delete_others_collectives',
    'edit_private_collectives',
    'edit_others_news_items',
    'delete_news_items',
    'delete_private_news_items',
    'delete_published_news_items',
    'delete_others_news_items',
    'edit_private_news_items',
    'edit_others_press_items',
    'delete_press_items',
    'delete_private_press_items',
    'delete_published_press_items',
    'delete_others_press_items',
    'edit_private_press_items',
];

return [
    'administrator' => array_values(array_unique(array_merge($editorCapabilities, $administratorExtraCapabilities))),
    'editor' => $editorCapabilities,
];
